### ISSUE TITLE
Roadmap to 0.1.0

### ISSUE THREAD

**Issue by dfilatov** [react-bem/react-bem#1]
- [ ] Move to es2015
- [ ] Introduce codestyle linters and checkers (#3)
- [ ] Move to react 0.14
- [ ] Split into two packages: `react-bem` and `react-bem-dom`
- [ ] Add support of custom class-naming schemes
- [ ] Add tests and coverage

**Comment by nezed** [comment]
- [ ] Availability as es7 class decorator
- [ ] Stateless components wrapper

Optional utils support:
- [ ] es2015 class methods auto-bind
- [ ] Freezing class instance
- [ ] Parent class-instance availability in `.prop`
- [ ] ~~An @artemshitov idea:~~
  
  > Each `.props` and `.state` properties names begin with `m_` becomes a modificators in className

**Comment by dfilatov** [comment]
> Each .props and .state properties names begin with m_ becomes a modificators in className

I don't like this idea. It looks like you pass private variable.

**Comment by nezed** [comment]
> > Each .props and .state properties names begin with m_ becomes a modificators in className
> 
> I don't like this idea. It looks like you pass private variable.

I think it looks like private variable becomes a part of view 😉

But it makes the place the appearance of a modifier is not obvious and can produce problems in large projects.

**Comment by dfilatov** [comment]
To avoid a mess, only component itself is responsible to manipulate it's modifiers.

**Comment by nezed** [comment]
About utils and extensions, they can be provided in default-exported fn, which can inject functions into react-bem.

ES6 modules capable ES5 example 😜

``` js
exports.__esModule = true;
module.exports = exports["default"] = config;
/**
 * @param {Object[]} array of `config` objects
 */
function config( array ) {
    // configure
};

module.exports.Component = function Component() {}
```

Config argument can be object like

``` js
/**
 * @namespace config
 * @property classNameFactory( block, [elem], [mods], [mix] )
 * @property beforeConstruct( reactClassSpecificationOrConstructor )
 * @property afterConstruct( reactClassInstance )
 * @property beforeCreateElement( reactClassInstance, elementJson )
 * @property beforeCreateBlock( reactClassInstance, blockJson )
 */
```

It makes possible to use all proposed for now utils

**Comment by dfilatov** [comment]
What are `beforeConstruct`, `afterConstruct`, `beforeCreateElement`, `beforeCreateBlock` for?

**Comment by nezed** [comment]
Example of util `parent instance in prop`

``` js
// user-file.js
var ReactBEM = require('react-bem')([{
    beforeCreateBlock: function( self, json ) {
        json.props = Object.assign({
            __parent: self
        }, json.props)
    }
}])
```

``` js
// bemJsonToReact.js
function bemJsonToReact(json, curBlock, parent) {
//    …
        if(json.block) {
            config.beforeCreateBlock.forEach(function( fn ) {
                fn(parent, json)
            });
            return createBemComponent(json, parent);
        }
//    …
}
```

Example of `react class instance freeze`

``` js
// user-file.js
var ReactBEM = require('react-bem')([{
    afterConstruct: function( self ) {
        Object.freeze(self)
    }
}])
```

``` js
// createClass.js
function createClass(specification) {
    config.beforeConstruct.forEach(function( fn ) {
        fn(specification)
    });
//    …
    spec.render = function(/* … */) {/* … */};

    var instance = React.createClass(specification);

    config.afterConstruct.forEach(function( fn ) {
        fn(instance)
    });
}
```

(And same in es6 react class constructor)

Then we can provide utils like a 

``` js
var ReactBEM = require('react-bem')([
    require('react-bem-util1'),
    require('react-bem-util2')
])
```

Found the same way example 😃
[github.com/postcss/postcss#js-api](https://github.com/postcss/postcss#js-api)
